# -*- coding: utf-8 -*-
"""fst-lexical-to-plurals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3Xd5Y0dQ8ct0CbD2TnTBC8H3r1Vn3jF
"""

def pluralize_fst(word: str) -> str:
    state = 'START'
    root, suffix = word.split("^")

    if state == 'START':
        if root[-1] in {'x', 's', 'z'} and suffix == 's#':
            state = 'CONSONANT_ENDING'
        else:
            state = 'PLURALIZE'

    if state == 'CONSONANT_ENDING':
        plural = root + 'es'
    elif state == 'PLURALIZE':
        plural = root + 's'

    return plural

print(pluralize_fst("fox^s#"))
print(pluralize_fst("boy^s#"))